import type { Metadata } from "next";
import "./globals.css";
import { HeaderComponent } from '@/components';
import LeftComponent from "@/components/LeftComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex flex-col overflow-hidden">
          <HeaderComponent />
          <div className="h-screen flex items-center">
            <LeftComponent />
            <main className="flex-1 overflow-y-scroll p-4 bg-dark snap-y snap-mandatory h-screen ">
              {children}
            </main>
          </div>

        </div>
      </body>
    </html>
  );
}
